# netlify.toml
[build]
  command   = "npm run build"
  publish   = "out"           # the folder Next.js will write when using output: 'export'

[build.environment]
  # prevent Netlify’s Next.js plugin from running at all
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from   = "/ord"
  to     = "https://s-kul-ord.lovable.app/"
  status = 200
  force  = true

[[redirects]]
  from   = "/ord/*"
  to     = "https://s-kul-ord.lovable.app/:splat"
  status = 200
  force  = true
